package Map;

import java.awt.*;
import java.io.*;
import javax.imageio.ImageIO;
import javax.swing.*;

public class MapGenerator {

    public static void main(String[] args) {
        try {
            Image greenSquare = ImageIO.read(new File("Image/green.png"));
            Image yellowSquare = ImageIO.read(new File("Image/yellow.jpg"));
            Image blueSquare = ImageIO.read(new File("Image/blue.png"));
            Image redSquare = ImageIO.read(new File("Image/red.jpg"));

            Board board = new Board(greenSquare, yellowSquare, blueSquare, redSquare, 8);

            //add pieces to board
            board.addPiece(new ImageIcon("Image/player.gif"), "4-4");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
    }
}
